// <auto-generated />
using System;
using GeneticAlgNetControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeneticAlgNetControl.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191023075716_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("GeneticAlgNetControl.Data.Models.Algorithm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AverageFitnessOverIterations")
                        .HasColumnType("TEXT");

                    b.Property<string>("BestFitnessOverIterations")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentIteration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentIterationWithoutImprovement")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateTimeEnded")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTimePeriods")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeStarted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edges")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPopulation")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumIterations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumIterationsWithoutImprovement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumPathLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nodes")
                        .HasColumnType("TEXT");

                    b.Property<double>("PercentageElite")
                        .HasColumnType("REAL");

                    b.Property<double>("PercentageRandom")
                        .HasColumnType("REAL");

                    b.Property<int>("PopulationSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredNodes")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProbabilityMutation")
                        .HasColumnType("REAL");

                    b.Property<int>("RandomGenesPerChromosome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetNodes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Algorithms");
                });
#pragma warning restore 612, 618
        }
    }
}
