// <auto-generated />
using System;
using GeneticAlgNetControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeneticAlgNetControl.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeneticAlgNetControl.Data.Models.Algorithm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CrossoverType")
                        .HasColumnType("int");

                    b.Property<int>("CurrentIteration")
                        .HasColumnType("int");

                    b.Property<int>("CurrentIterationWithoutImprovement")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateTimeEnded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateTimePeriods")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTimeStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Edges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumIterations")
                        .HasColumnType("int");

                    b.Property<int>("MaximumIterationsWithoutImprovement")
                        .HasColumnType("int");

                    b.Property<int>("MaximumPathLength")
                        .HasColumnType("int");

                    b.Property<int>("MutationType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentageElite")
                        .HasColumnType("float");

                    b.Property<double>("PercentageRandom")
                        .HasColumnType("float");

                    b.Property<string>("Population")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopulationSize")
                        .HasColumnType("int");

                    b.Property<string>("PreferredNodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProbabilityMutation")
                        .HasColumnType("float");

                    b.Property<int>("RandomGenesPerChromosome")
                        .HasColumnType("int");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetNodes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Algorithms");
                });
#pragma warning restore 612, 618
        }
    }
}
